### ISSUE TITLE
Misleading exception thrown when Hub error doesn't contain a JSON body

### ISSUE THREAD

**Issue by fteufel** [polaris-hub/polaris#149]
### Polaris version

0.7.3

### Python Version

3.10

### Operating System

Linux

### Installation

pip

### Description

A seemingly standard benchmark upload fails. Not sure why exactly.

```
⠋ Uploading benchmark...2024-07-22 16:49:03.027 | INFO     | polaris._mixins:md5sum:27 - Computing the checksum. This can be slow for large datasets.
💥 ERROR: Failed to upload benchmark. 
Traceback (most recent call last):
  File "/novo/users/fegt/BEND/scripts/upload_polaris_benchmarks.py", line 62, in <module>
    benchmark.upload_to_hub(owner='mlls', visibility='public')
  File "/novo/users/fegt/miniconda3/envs/bend/lib/python3.10/site-packages/polaris/benchmark/_base.py", line 499, in upload_to_hub
    return client.upload_benchmark(self, access=access, owner=owner)
  File "/novo/users/fegt/miniconda3/envs/bend/lib/python3.10/site-packages/polaris/hub/client.py", line 657, in upload_benchmark
    response = self._base_request_to_hub(url=url, method="PUT", json=benchmark_json)
  File "/novo/users/fegt/miniconda3/envs/bend/lib/python3.10/site-packages/polaris/hub/client.py", line 171, in _base_request_to_hub
    response = response.json()
  File "/novo/users/fegt/miniconda3/envs/bend/lib/python3.10/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/novo/users/fegt/miniconda3/envs/bend/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/novo/users/fegt/miniconda3/envs/bend/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/novo/users/fegt/miniconda3/envs/bend/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Steps to reproduce

```python
dataset = po.load_dataset("mlls/bend-histone-modification")
dataset.cache()
split = [
    np.where(~dataset.table['chromosome'].isin(['chr1', 'chr8', 'chr9', 'chr2', 'chr4']))[0].tolist(),
    {
    "test" :  np.where(dataset.table['chromosome'].isin(['chr1', 'chr8', 'chr9']))[0].tolist(),
    "valid" : np.where(dataset.table['chromosome'].isin(['chr2', 'chr4']))[0].tolist(),
}
]

benchmark = SingleTaskBenchmarkSpecification(
    name='bend_histone_modification',
    dataset=dataset,
    target_cols="label",
    input_cols=["sequence"],
    split=split,
    metrics="roc_auc",
)
train, test = benchmark.get_train_test_split()
x = next(iter(train))
print(x)

benchmark.upload_to_hub(owner='mlls', visibility='public')
```

**Comment by cwognum** [comment]
Hey @fteufel ,

Thanks again for reporting. And thank you for your patience as we work through the issues you help us spot! You're making valuable contributions to Polaris that are not going unnoticed! 🙏 

I just wanted to drop in here and let you know that we've been investigating this issue. There appear to be two issues: 
- We have not yet run elaborate tests with benchmarks this large. It appears the `split` field is the issue here! The request you're sending to Vercel throws a `413 Request entity too large`. We actually documented the issue in https://github.com/polaris-hub/polaris-hub/issues/382#issuecomment-2227088205, but didn't think we would run into it this quickly.  
- As a side effect of the first issue, the thrown error is a bit misleading. The issue is that we assume (see [here](https://github.com/polaris-hub/polaris/blob/main/polaris/hub/client.py#L169-L171)) that if the error thrown is not a 500, it's an error we've thrown ourselves on the Hub and that it thus has a JSON field. This is not true in this case, leading to the application crashing at a weird spot and a misleading, confusing error message. 

After the ICML launch, our primary focus is supporting larger datasets and benchmarks, but in the meantime I'm afraid we can't support this benchmark yet.
