### ISSUE TITLE
Login OAuth not working as expected

### ISSUE THREAD

**Issue by hmacdope** [polaris-hub/polaris#218]
### Polaris version

0.2.3

### Python Version

3.12

### Operating System

Linux

### Installation

mamba

### Description

Intermittent failure to login using `polaris login` which then routes through Clerk service

Tries to force Github or Google OAuth login which will then fail

### Steps to reproduce

Follow the demo below to reproduce

https://www.loom.com/share/ebc06f6a01074bbd9cd73d705f5b8bf0?sid=a7ca05b3-6e69-4871-aa68-a1882d2d7580

**Comment by cwognum** [comment]
@hmacdope Thanks for the detailed bug report. The video is super, super helpful! ✨ 

Looking at the redirect, it seems you're being taken to `pure-whippet-77/...`. That to me indicates that you're logging in against the dev environment we have for Clerk - our user management platform. That would also explain the error you're getting, because the dev environment has a allowlist in place.

I'm not sure _why_ you're running into this though... You would have had to change the [config](https://github.com/polaris-hub/polaris/blob/main/polaris/hub/settings.py) somehow. Could it be that you have some `.env` file in your working directory that could be interfering?

**Comment by hmacdope** [comment]
I don't think there is an env file hanging about, let me triple check but seems unlikely that I would have the exact settings present.

**Comment by hmacdope** [comment]
Ah that makes sense, closing!
