### ISSUE TITLE
Bug in saving User Attributes to the Zarr archive

### ISSUE THREAD

**Issue by cwognum** [polaris-hub/polaris#75]
# Context

To create signed URLs for the directory-based file format called Zarr, Polaris implements a [custom Zarr storage class](https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.FSStore) called [`PolarisFS`](https://github.com/polaris-hub/polaris/blob/main/polaris/hub/polarisfs.py).

# Description

Zarr supports [User Attributes](https://zarr.readthedocs.io/en/stable/tutorial.html#user-attributes), however our current implementation fails if we try to read the user attributes: 
```
cat /storage/dataset/polaris/hello-world/test8.zarr/.zattrs
< GET https://874f02b9d981bd6c279e979c0d91c4b4.r2.cloudflarestorage.com/polaris-test/dataset/polaris/hello-world/test8.zarr/.zattrs?X-Amz-Expires=3600&X-Amz-Date=20240307T190323Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=a903e7f05ccdad53ffcb76fc78754299%2F20240307%2Fauto%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=f744d109864c4fa419a6156283cbbedfe15583a7c033448415a51002739426c5
< host: 874f02b9d981bd6c279e979c0d91c4b4.r2.cloudflarestorage.com
< accept: */*
< accept-encoding: gzip, deflate, br
< connection: keep-alive
< user-agent: python-httpx/0.26.0
< content-type: application/octet-stream
< x-amz-content-sha256: UNSIGNED-PAYLOAD
< x-amz-date: 20240307T190323Z
< 
< b''

>  404 Not Found
> date: Thu, 07 Mar 2024 19:03:24 GMT
> content-type: application/xml
> connection: keep-alive
> vary: Accept-Encoding
> server: cloudflare
> cf-ray: 860cd866bd053a02-YYZ
> content-encoding: gzip
> content-length: 131
> 
> <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error> 
```

It seems that the user attributes should be written to a file called `.zattrs` but that this file doesn't exist. This should be investigated further though. 

# Acceptance Criteria

- [ ] We can read and write User Attributes to and from a Zarr archive

# Links
- First implementation of the Zarr dataset is tracked here: https://github.com/polaris-hub/polaris-hub/issues/266

**Comment by lmtroper** [comment]
The problem is that the Zarr storage implementation assumes that the `.zattrs` file already exists in the file system, and will pass the path to `cat_file` to read the contents. It has no problem creating other required files such as `.zgroup` or `.zarray`. In the screenshot below, I've printed out the FS functions called by the Zarr implementation and printing out the data returned from `cat_file`:

![Image](https://github.com/polaris-hub/polaris/assets/72565412/463e484d-9bca-4377-978f-215e3907c949)

Some of the ways I've explored solving this bug:
- I've checked for relevant Github issues but there's no issues about `.zattrs` file with FSStore implementations
- My next step was to verify that the Zarr implementation wasn't using any other FS functions (that are unimplemented on our end) to create the `.zattrs` file. I tried out the functions: `pipe`, `mkdir`, `mkdirs`, `put`, `put_file`. As seen in the screenshot, the only one of these being used by the Zarr implementation that we haven't defined for PolarisFS is `mkdirs`. (Maybe something more happens in that step?)

**Comment by cwognum** [comment]
For reference, we have been using the following "test case":

<details><summary>Details</summary>
<p>

```python

def test(root: zarr.Group, path: str, cloudflare: bool):

    if cloudflare: 
        fs = s3fs.S3FileSystem(
            key=..., 
            secret=..., 
            client_kwargs=dict(endpoint_url=...), 
            s3_additional_kwargs=dict(ACL="private"), # <- this is neccessary for writing. 
        )
    else: 
        fs, _ = fsspec.core.url_to_fs(path)
        
    try:
        toy_data = np.random.random((10, 100))

        print("Writing toy data")
        root.array("arr", toy_data)
        print("Writing user attr 1")
        root.attrs["A"] = 1
        print("Writing user attr 2")
        root.attrs["B"] = 2
    
        print("Zarr Archive content:", fs.ls(path))
        with fs.open(os.path.join(path, ".zattrs"), "r") as f: 
            data = json.load(f)
        
        print("Attributes", data)

        print("Attributes through Zarr", root.attrs["A"], root.attrs["B"])
    
    finally:

        if cloudflare:
            fs.rm(path, recursive=True)

```

local, for reference: 
```python
with TemporaryDirectory() as tmpdir: 
    path = os.path.join(tmpdir, "data.zarr")
    root = zarr.open(path, "w")
    test(root, path, False)
```
</p>

On the Hub
```python
with PolarisHubClient() as client: 
    root = client.open_zarr_file(owner="polaris", name="hello-world", path="test2.zarr", mode="w")
    test(root, "polaris-test/dataset/polaris/hello-world/test2.zarr", True)
```
</p>
</details>

**Comment by cwognum** [comment]
After testing it with clean repositories, this works! Seems we had a corrupted local state somehow!
