### ISSUE TITLE
Problem with POlaris installation

### ISSUE THREAD

**Issue by SarahKarbalaeiKhani** [polaris-hub/polaris#97]
### Polaris version

0.2.6

### Python Version

3.10

### Operating System

Mac

### Installation

pip install polaris-lib

### Description

The installation command runs through. However, there seems like nothing gets installed.

### Steps to reproduce

pip install polaris-lib

**Comment by cwognum** [comment]
Hi @SarahKarbalaeiKhani, 

Based on the screenshot you shared with me privately, it seems you were actually using Python 3.9.7. There's a known issue in that specific Python version that broke some things in Pydantic, see https://github.com/pydantic/pydantic/issues/7544. 

This should be fixed if you upgrade to a newer version of Python. 

For future reference, the error was: 
```
TypeError: StringConstraints() takes no arguments
```
which happens due to [this line](https://github.com/polaris-hub/polaris/blob/main/polaris/utils/types.py#L52). It also thus happens on importing Polaris.
